name: React build & deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Run scripts in EC2 server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/chopsticks/HairHaeJo-Frontend
            git pull
            npm install
            export NODE_OPTIONS=--max_old_space_size=800
            npm run build
